title: Software Development Lifecycle - Queensland Department of Education
description: Values, principals and practices used in developing digital applications for the Queensland Department of Education.
baseurl: /SDLC/
footer_content: "Copyright &copy; 2025 Queensland Department Of Education"

theme: minima
minima:
  nav_pages:
    - index.md
    - values.md
    - principals.md
    - practices.md
    - methodologies.md





